### ISSUE TITLE
Short example of use

### ISSUE THREAD

**Issue by ppollet73** [schirinos/slagger#1]
Hello,
I'm very interested in using slagger, however I do not know how to start, could you please provide a short example on how to do ?

Thanks in advance

Pierre

**Comment by torrespri** [comment]
Hello, 
I don't know how start to use slagger.
Any example or documentation?
Thanks

Pepe

**Comment by schirinos** [comment]
Refactored middleware to use Swagger annotations to generate the swagger json. Also updated readme with usage examples.
